.PHONY: build clean

BUILD_DIR := $(shell mkdir -p build.PSV)build.PSV
BUILD_DIR_BACKEND := $(shell mkdir -p build.PSV/backend)build.PSV/backend

INC := $(wildcard *.h) $(wildcard ../include/*.h) $(wildcard ../../cpymo/*.h)

SRC_CPYMO := $(wildcard ../../cpymo/*.c)
SRC_BACKEND := $(wildcard *.c) 
OBJS_CPYMO := $(patsubst %.c, $(BUILD_DIR)/%.o, $(notdir $(SRC_CPYMO)))
OBJS_BACKEND := $(patsubst %.c, $(BUILD_DIR_BACKEND)/%.o, $(notdir $(SRC_BACKEND)))
CC := arm-vita-eabi-gcc

CFLAGS := \
	-I$(CURDIR)/../include \
	-I$(CURDIR)/../../cpymo \
	-I$(CURDIR)/../../stb \
	-I$(CURDIR)/build.FFmpeg.PSV/include \
	-I$(CURDIR)/../../endianness.h \
	-D__PSV__ \
	-DUSE_GAME_SELECTOR \
	-DSDL2_AUDIO_DEFAULT_FREQ=44100 \
	-DSDL2_AUDIO_DEFAULT_FORMAT_SDL=AUDIO_S16 \
	-DSDL2_AUDIO_DEFAULT_FORMAT_CPYMO=cpymo_backend_audio_s16 \
	-DGAME_SELECTOR_DIR="\"ux0:/pymogames/\"" \
	-DGAME_SELECTOR_FONTSIZE=24 \
	-DGAME_SELECTOR_EMPTY_MSG_FONTSIZE=28 \
	-DGAME_SELECTOR_COUNT_PER_SCREEN=7 \
	-DSCREEN_WIDTH=960 \
	-DSCREEN_HEIGHT=544 \
	-DDONT_PASS_PATH_TO_FFMPEG \
	-DNDEBUG \
	-O3 \
	-Wall

define compile
	@echo "$(notdir $1)"
	@$(CC) -c -Wl,-q $1 -o $2 $(CFLAGS)
endef

build: cpymo.vpk

clean:
	@rm -fr $(BUILD_DIR)
	@rm -fr cpymo.vpk

$(BUILD_DIR_BACKEND)/%.o: %.c $(INC)
	$(call compile,$<,$@)

$(BUILD_DIR)/%.o: ../../cpymo/%.c $(INC)
	$(call compile,$<,$@)

$(BUILD_DIR)/cpymo.elf: $(OBJS_BACKEND) $(OBJS_CPYMO)
	@echo "Linking..."
	@$(CC) -Wl,-q $^ -o $@ \
		-L$(CURDIR)/build.FFmpeg.PSV/lib \
		-Xlinker "-(" \
		-lSDL2 \
		-lSDL2main \
		-lSceDisplay_stub \
		-lSceCtrl_stub \
		-lSceAudio_stub \
		-lSceAudioIn_stub \
		-lSceSysmodule_stub \
		-lSceGxm_stub \
		-lSceCommonDialog_stub \
		-lSceAppMgr_stub \
		-lSceTouch_stub \
		-lSceHid_stub \
		-lSceMotion_stub \
		-lavcodec -lavformat -lavutil -lswresample \
		-lm \
		-Xlinker "-)" \
		-L$(VITASDK)/arm-vita-eabi/lib \
		-Wl,-z,nocopyreloc
	@arm-vita-eabi-strip -g $@

$(BUILD_DIR)/cpymo.velf: $(BUILD_DIR)/cpymo.elf
	@vita-elf-create $< $@

$(BUILD_DIR)/param.sfo: 
	@vita-mksfoex -s TITLE_ID="CPYMO0002" "CPyMO" $@

$(BUILD_DIR)/eboot.bin: $(BUILD_DIR)/cpymo.velf
	@vita-make-fself -s -ss $< $@

cpymo.vpk: $(BUILD_DIR)/param.sfo $(BUILD_DIR)/eboot.bin
	@vita-pack-vpk \
		-s $(BUILD_DIR)/param.sfo \
		-b $(BUILD_DIR)/eboot.bin $@ \
		-a psv-icon0.png=sce_sys/icon0.png \
		-a psv-pic0.png=sce_sys/pic0.png \
		-a psv-startup.png=sce_sys/livearea/contents/startup.png \
		-a psv-template.xml=sce_sys/livearea/contents/template.xml \
		-a psv-bg0.png=sce_sys/livearea/contents/bg0.png
	@echo "=> $@"

