.PHONY: build clean

BUILD_DIR := $(shell mkdir -p build.PSV)build.PSV
BUILD_DIR_BACKEND := $(shell mkdir -p build.PSV/backend)build.PSV/backend

INC := $(wildcard *.h) $(wildcard ../include/*.h) $(wildcard ../../cpymo/*.h)

SRC_CPYMO := $(wildcard ../../cpymo/*.c)
SRC_BACKEND := $(wildcard *.c) 
OBJS_CPYMO := $(patsubst %.c, $(BUILD_DIR)/%.o, $(notdir $(SRC_CPYMO)))
OBJS_BACKEND := $(patsubst %.c, $(BUILD_DIR_BACKEND)/%.o, $(notdir $(SRC_BACKEND)))
CC := arm-vita-eabi-gcc

CFLAGS := \
	-I$(CURDIR)/../include \
	-I$(CURDIR)/../../cpymo \
	-I$(CURDIR)/../../stb \
	-I$(CURDIR)/../../endianness.h \
	-I$(VITASDK)/arm-vita-eabi/include \
	-I$(VITASDK)/arm-vita-eabi/include/SDL2 \
	-D__PSV__ \
	-DDISABLE_MOVIE \
	-DDISABLE_FFMPEG_AUDIO \
	-DENABLE_SDL2_MIXER_AUDIO_BACKEND \
	-DUSE_GAME_SELECTOR \
	-DGAME_SELECTOR_DIR="\"ux0:/pymogames/\"" \
	-DGAME_SELECTOR_FONTSIZE=24 \
	-DGAME_SELECTOR_EMPTY_MSG_FONTSIZE=28 \
	-DGAME_SELECTOR_COUNT_PER_SCREEN=7 \
	-DSCREEN_WIDTH=960 \
	-DSCREEN_HEIGHT=544 \
	-O3 \
	-Wall

define compile
	@echo "$(notdir $1)"
	@$(CC) -c -Wl,-q $1 -o $2 $(CFLAGS)
endef

build: eboot.bin

clean:
	@rm -fr $(BUILD_DIR)
	@rm -fr eboot.bin

$(BUILD_DIR_BACKEND)/%.o: %.c $(INC)
	$(call compile,$<,$@)

$(BUILD_DIR)/%.o: ../../cpymo/%.c $(INC)
	$(call compile,$<,$@)

$(BUILD_DIR)/cpymo.elf: $(OBJS_BACKEND) $(OBJS_CPYMO)
	@echo "Linking..."
	@$(CC) -Wl,-q $^ -o $@ \
		-Xlinker "-(" \
		-lSDL2 \
		-lSDL2main \
		-lSceDisplay_stub \
		-lSceCtrl_stub \
		-lSceAudio_stub \
		-lSceAudioIn_stub \
		-lSceSysmodule_stub \
		-lSceGxm_stub \
		-lSceCommonDialog_stub \
		-lSceAppMgr_stub \
		-lSceTouch_stub \
		-lSceHid_stub \
		-lSceMotion_stub \
		-lSDL2_mixer \
		-lmikmod \
		-lFLAC \
		-logg \
		-lmpg123 \
		-lvorbis \
		-lvorbisfile \
		-lm \
		-Xlinker "-)" \
		-L$(VITASDK)/arm-vita-eabi/lib \
		-Wl,-z,nocopyreloc
	@arm-vita-eabi-strip -g $@

$(BUILD_DIR)/cpymo.velf: $(BUILD_DIR)/cpymo.elf
	@vita-elf-create $< $@

eboot.bin: $(BUILD_DIR)/cpymo.velf
	@vita-make-fself -s -ss $< $@
	@echo "==> eboot.bin"
