BUILD_DIR = build.Win32

!ifndef TARGET
TARGET = cpymo-tool.exe
!endif

SRC = *.c

build: $(TARGET)
	@echo Built $(TARGET)

run: build
	cpymo-tool.exe

clean:
	@rd /S /Q $(BUILD_DIR)
	@del /f /s /q $(TARGET)
	
dirs:
	@if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)

$(TARGET): $(SRC) dirs
	@$(CC) $(SRC) /Fe$(TARGET) /Fo$(BUILD_DIR)/ \
		-I../cpymo \
		-I../stb \
		-I../endianness.h \
		/DNDEBUG \
		/utf-8 \
		/O2 /Os /MP /nologo \
		/link /RELEASE

